Remove unused dependencies from Manifest.MF
eclipse-equinox/equinox.bundles pull request #19
Opened 2022-04-20 18:04 UTC by HannesWell

This also allows to re-enable `org.eclipse.equinox.region.tests`.
Lets see if there are test failures to fix.

2022-04-20 18:43 UTC, tjwatson commented
> This also allows to re-enable `org.eclipse.equinox.region.tests`.
> Lets see if there are test failures to fix.

That will not work without aspectj bundles because of the JAR `org.eclipse.equinox.region.tests/stubs/org.eclipse.virgo.teststubs.osgi.jar`

 I'm sure we can create custom proxies to do something here that is similar.  I had this on my todo list long ago but never had time to dig in.

2022-04-20 21:34 UTC, HannesWell commented
> > This also allows to re-enable `org.eclipse.equinox.region.tests`.
> > Lets see if there are test failures to fix.
> 
> That will not work without aspectj bundles because of the JAR `org.eclipse.equinox.region.tests/stubs/org.eclipse.virgo.teststubs.osgi.jar`

Too bad. One of my motivations was to use Tycho-pomless for equinox-bundles too. We could then just build all projects in the bundles folder and would not have to list them one by one.

But while working on it I realized that this would benefit from some more preliminary work, mainly fixing warnings, which will be simpler once the osgi-sources are replaced by the Maven artifacts. Which brings me back to my initial task.
Looking at the amount of changes in the pom I also think this PR would be better done after Tycho-pomless is used.

> I'm sure we can create custom proxies to do something here that is similar. I had this on my todo list long ago but never had time to dig in.

Would you be fine to disable all failing tests for now so that the project can at least participate in the build?

With that being said I think it would be better to re-enable `org.eclipse.equinox.region.tests` in a separate change and to put this one on hold until equinox-bundles uses Tycho pomless.

2022-06-16 09:16 UTC, laeubi requested changes
We recently moved the repository content to https://github.com/eclipse-equinox/equinox would you be so kind to open your PR for the new repository?

2022-06-16 22:48 UTC, HannesWell commented
> We recently moved the repository content to https://github.com/eclipse-equinox/equinox would you be so kind to open your PR for the new repository?

I will just recreate this later, once some more other works is completed that make this change simpler.

2022-06-16 22:48 UTC, closed without merging